<?php

namespace AppBundle\Repository;

/**
 * ActivePeriodeZoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivePeriodeZoneRepository extends \Doctrine\ORM\EntityRepository
{
}
