<?php

namespace AppBundle\Repository;

/**
 * HistoriqueZoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueZoneRepository extends \Doctrine\ORM\EntityRepository
{
}
