app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation
background:
    type:     rest
    resource: AppBundle\Controller\BackgroundController
    
post_backgrounds:
    path: /Backgrounds
    defaults: {_controller: AppBundle:Background:postBackgrounds}
    
patch_backgrounds:
    path: /Backgrounds/{id}
    defaults: {_controller: AppBundle:Background:patchBackgrounds}
    
active_periode:
    type:     rest
    resource: AppBundle\Controller\ActivePeriodeZoneController
    
post_active_periodes:
    path: /Zones/{id}/activePeriodes
    defaults: {_controller: AppBundle:ActivePeriodeZone:postActivePeriodes}
    
delete_zone:
    path: /Zones/{id}
    defaults: {_controller: AppBundle:Zone:removeZone}